app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('hi/',hi,name='hi'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('bye/',bye,name='bye'),

]

project13/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hi(request):
    return render(request,'hi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello bye html page</h1>
        <h1>this is bye html page</h1>
        <a href="{% url 'app1:hi' %}">this page navigate to hi html page</a>
    </center>
    
</body>
</html>

templates/hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello hi html page</h1>
        <h1>this is hi html page</h1>

        <a href="{% url 'app2:bye' %}"> this page navigate to bye page</a>
    </center>
    
</body>
</html>